<a href="https://colab.research.google.com/github/utkarsh6174/ML/blob/main/complete_numpy_tutorial_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

system specifications

In [ ]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi its
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
address sizes

In [ ]:
!cat /proc/meminfo


MemTotal:       13286964 kB
MemFree:         9294080 kB
MemAvailable:   12234640 kB
Buffers:          114644 kB
Cached:          2969396 kB
SwapCached:            0 kB
Active:           451192 kB
Inactive:        3201824 kB
Active(anon):       2456 kB
Inactive(anon):   569592 kB
Active(file):     448736 kB
Inactive(file):  2632232 kB
Unevictable:           8 kB
Mlocked:               8 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               580 kB
Writeback:             0 kB
AnonPages:        569016 kB
Mapped:           432904 kB
Shmem:              3048 kB
KReclaimable:     185236 kB
Slab:             227376 kB
SReclaimable:     185236 kB
SUnreclaim:        42140 kB
KernelStack:        5776 kB
PageTables:         8728 kB
SecPageTables:         0 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6643480 kB
Committed_AS:    2763392 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       12264 kB
VmallocChunk:    

In [ ]:
import numpy as np



List vs Numpy  - time taken

In [ ]:
from time import process_time


Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()
python_list = [i+5 for i in python_list]

end_time = process_time()
print(end_time - start_time)

0.0007371529999999904


Time taken by a numpy

In [ ]:
from IPython.utils import process
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array = np_array + 5

end_time = process_time()

print(end_time - start_time)

0.0001866999999999841


Numpy Arrays

In [ ]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array  = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
 #creating a 1D array
 a = np.array([1,2,3,4])
 print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4),(6,7,8,9)])
print(b)
b.shape

[[1 2 3 4]
 [6 7 8 9]]


(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial placeholders in numpy arrays

In [ ]:
#create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy arrays of ones
y = np.ones((2,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#create an identitiy matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.99817641 0.05460394 0.96571981 0.98943723]
 [0.71969656 0.97084407 0.90297308 0.71662807]
 [0.7435263  0.80768097 0.84963697 0.56184168]]


In [ ]:
 #random integers values array within a specific range
 c = np.random.randint(10,100,(3,5))
 print(c)

[[62 16 69 30 96]
 [62 43 36 57 55]
 [61 54 48 99 34]]


In [ ]:
 # array of evenly spaced values --->specifying the number of values required
 d = np.linspace(10,30,7)
 print(d)

[10.         13.33333333 16.66666667 20.         23.33333333 26.66666667
 30.        ]


In [ ]:
#array of evenly spaced values --> specifying the step
e = np.arange(10,30,2)
print(e)

[10 12 14 16 18 20 22 24 26 28]


In [ ]:
#convert a list to a numpy array
list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[26 72 87 26 17]
 [39 78 69 84 75]
 [43 72 36 34 10]
 [10 16 33 30 71]
 [50 61 10 71 30]]


In [ ]:
#array dimension
print(c.shape)

(5, 5)


In [ ]:
#number of dimensions
print(c.ndim)

2


In [ ]:
#number of elements in an array
print(c.size)

25


In [ ]:
#checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [5,6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
print(a)

b = np.random.randint(0,10,(3,3))
print(b)
print(np.add(a,b))
print(np.subtract(a,b))

[[9 4 4]
 [0 5 9]
 [4 6 5]]
[[8 1 9]
 [9 6 8]
 [6 7 3]]
[[17  5 13]
 [ 9 11 17]
 [10 13  8]]
[[ 1  3 -5]
 [-9 -1  1]
 [-2 -1  2]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)


[[8 5 5]
 [5 9 4]]


In [ ]:
#transpose
trans = np.transpose(array)
print(trans)

[[8 5]
 [5 9]
 [5 4]]


In [ ]:
trans2 = trans.T
print(trans)
print(trans2)

[[8 5]
 [5 9]
 [5 4]]
[[8 5 5]
 [5 9 4]]


In [ ]:
#reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 2 1]
 [7 1 8]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 2]
 [1 7]
 [1 8]]
(3, 2)
